

###################################################################################

spring.application.name=api

# Render necesita un puerto dinámico (y en local usará 8080)
server.port=${PORT:8080}

# La conexión a BD vendrá por variables de entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# ===== POOL DE CONEXIONES (HIKARI) =====

# Máximo de conexiones simultáneas a MySQL
spring.datasource.hikari.maximum-pool-size=3

# Mínimo de conexiones en reposo
spring.datasource.hikari.minimum-idle=1

# Tiempo máximo esperando una conexión (ms)
spring.datasource.hikari.connection-timeout=30000

# Tiempo máximo de vida de una conexión (ms)
spring.datasource.hikari.max-lifetime=1800000

# Tiempo máximo que una conexión puede estar inactiva (ms)
spring.datasource.hikari.idle-timeout=600000